server:
  port: 8086
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          # Account 서비스 라우팅
          - id: account-service
            predicates:
              - Path=/account/**
            uri: http://localhost:8080
            filters:
              # 임시로 인증 헤더 필터 제거
               - AddAuthenticationHeader
               # - RewritePath=/account/(?<segment>.*), /account/api/$\{segment}
            
          # Event 서비스 라우팅  
          - id: event-service
            predicates:
              - Path=/event/**
            uri: http://localhost:8081
            filters:
              # 임시로 인증 헤더 필터 제거
               - AddAuthenticationHeader
               # - RewritePath=/event/(?<segment>.*), /event/api/$\{segment}
              
          # Payment 서비스 라우팅
          - id: payment-service
            predicates:
              - Path=/payment/**
            uri: http://localhost:8082
            filters:
               - AddAuthenticationHeader
               # - RewritePath=/payment/(?<segment>.*), /payment/api/$\{segment}
              
          # DID 서비스 라우팅
          - id: did-service
            predicates:
              - Path=/did/**
            uri: http://localhost:8083
            filters:
               - AddAuthenticationHeader
               # - RewritePath=/did/(?<segment>.*), /did/api/$\{segment}
              
          # Notification 서비스 라우팅
          - id: noti-service
            predicates:
              - Path=/noti/**
            uri: http://localhost:8084
            filters:
               - AddAuthenticationHeader
               # - RewritePath=/noti/(?<segment>.*), /noti/api/$\{segment}
              
          # BFF 서비스 라우팅
          - id: bff-service
            predicates:
              - Path=/bff/**
            uri: http://localhost:8085
            filters:
              # - AddAuthenticationHeader
              # - RewritePath=/bff/(?<segment>.*), /bff/api/$\{segment}

jwt:
  header: Authorization
  secretKey: cHlva2Vtb24tYWNjb3VudC1qd3Qtc2VjcmV0LWtleS0yMDI0LXZlcnktbG9uZy1zZWNyZXQta2V5LWZvci1zZWN1cml0eQ==
  expiresIn: 1800000
  mobileExpiresIn: 604800000

logging:
  level:
    root: info
    com.pyokemon.gateway_service: info
    
---
spring:
  config:
    activate:
      on-profile: "dev"
    import:
      - classpath:dev-config.yml
