server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: gatewaypassword
    key-store-type: PKCS12
    key-alias: gateway-service
    client-auth: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: /volume1/docker/pyokemon/gateway-service/logs/app.log
  level:
    root: debug


spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: account-service
            uri: http://account-service:8080

          - id: event-service
            uri: http://event-service:8081

          - id: payment-service
            uri: http://payment-service:8082

          - id: did-service
            uri: http://did-service:8083
              
          - id: noti-service
            uri: http://noti-service:8084
              
          - id: bff-service
            uri: http://bff-service:8085