server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: gatewaypassword
    key-store-type: PKCS12
    key-alias: gateway-service
    client-auth: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: /volume1/docker/pyokemon/gateway-service/logs/app.log
  level:
    root: debug